# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 489)
        MainWindow.setStyleSheet("background: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_Fname = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Fname.setGeometry(QtCore.QRect(50, 110, 251, 101))
        self.btn_Fname.setStyleSheet("font: 28pt \"Arial\";\n"
"border: 2px solid black;\n"
"border: 5px solid rgba(255,255,255,0%);\n"
"border-radius: 10px;\n"
"background: rgba(255,255,255,80%);")
        self.btn_Fname.setObjectName("btn_Fname")
        self.btn_Sname = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sname.setGeometry(QtCore.QRect(490, 110, 251, 101))
        self.btn_Sname.setStyleSheet("font: 28pt \"Arial\";\n"
"border: 2px solid black;\n"
"border: 5px solid rgba(255,255,255,0%);\n"
"border-radius: 10px;\n"
"background: rgba(255,255,255,80%);")
        self.btn_Sname.setObjectName("btn_Sname")
        self.btn_Press = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Press.setGeometry(QtCore.QRect(270, 320, 251, 101))
        self.btn_Press.setStyleSheet("font: 28pt \"Arial\";\n"
"border: 2px solid black;\n"
"border: 5px solid rgba(255,255,255,0%);\n"
"border-radius: 10px;\n"
"background: rgb(255, 232, 0);")
        self.btn_Press.setObjectName("btn_Press")
        self.lb_count = QtWidgets.QLabel(self.centralwidget)
        self.lb_count.setGeometry(QtCore.QRect(680, 40, 91, 21))
        self.lb_count.setStyleSheet("font: 16pt \"Arial\";\n"
"color: white;")
        self.lb_count.setObjectName("lb_count")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tặng quà"))
        self.btn_Fname.setText(_translate("MainWindow", "Name1"))
        self.btn_Sname.setText(_translate("MainWindow", "Name2"))
        self.btn_Press.setText(_translate("MainWindow", "Tặng Quà"))
        self.lb_count.setText(_translate("MainWindow", "COUNT: 44"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
